name: DRL
channels:
  - conda-forge
dependencies:
- python>=3.5
- anaconda
- six
- h5py
- matplotlib==1.4.3
- seaborn>=0.7.1
- Pillow>=3.3.1
- PyOpenGL>=3.1.0
- glances>=2.6.2
- pytest-cov>=2.3.1
- pytest-xdist>=1.15.0
- pip:
  - codacy-coverage>=1.3.3
  - mem_top==0.1.5
  - atari_py>=0.0.18
  - cmake==0.6.0
  - tensorflow>=1.0.0
  - Keras>=1.2.2,<2.0.0
  - "--editable=git+https://github.com/openai/gym.git#egg=gym[all]"
